name: rpf
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=3.6.1
  - aom=3.4.0
  - appdirs=1.4.4
  - appnope=0.1.3
  - asttokens=2.0.8
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - certifi=2022.6.15
  - charset-normalizer=2.1.1
  - colorama=0.4.5
  - cycler=0.11.0
  - dataclasses=0.8
  - decorator=5.1.1
  - executing=0.10.0
  - expat=2.4.8
  - fastapi=0.81.0
  - ffmpeg=5.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gettext=0.19.8.1
  - gmp=6.2.1
  - gnutls=3.7.7
  - h11=0.13.0
  - icu=70.1
  - idna=3.3
  - ipython=8.4.0
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.13
  - libffi=3.4.2
  - libflac=1.3.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.3
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.37
  - librosa=0.9.2
  - libsndfile=1.0.31
  - libsqlite=3.39.2
  - libtasn1=4.19.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mido=1.2.10
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - ncurses=6.3
  - nettle=3.8.1
  - openh264=2.3.0
  - openjpeg=2.5.0
  - openssl=3.0.5
  - p11-kit=0.24.1
  - packaging=21.3
  - parso=0.8.3
  - pathspec=0.10.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2.2
  - platformdirs=2.5.2
  - pooch=1.6.0
  - prompt-toolkit=3.0.30
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.13.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - pysoundfile=0.10.3.post1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - readline=8.1.2
  - redis=3.5.3
  - requests=2.28.1
  - resampy=0.4.0
  - setuptools=65.3.0
  - six=1.16.0
  - stack_data=0.5.0
  - starlette=0.19.1
  - svt-av1=1.2.1
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tomli=2.0.1
  - tqdm=4.64.0
  - traitlets=5.3.0
  - transitions=0.8.11
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - wheel=0.37.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - aiofiles==0.8.0
    - aioredis==2.0.1
    - aiosqlite==0.17.0
    - async-timeout==4.0.2
    - audioread==3.0.0
    - babel==2.10.3
    - bcrypt==4.0.0
    - brotlipy==0.7.0
    - cffi==1.15.1
    - click==8.1.3
    - cryptography==37.0.1
    - fonttools==4.37.1
    - greenlet==1.1.3
    - httptools==0.4.0
    - iso8601==1.0.2
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - kiwisolver==1.4.4
    - llvmlite==0.38.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - mypy-extensions==0.4.3
    - numba==0.55.2
    - numpy==1.22.4
    - pendulum==2.1.2
    - pillow==9.2.0
    - pyaudio==0.2.12
    - pyclean==2.2.0
    - pydantic==1.9.2
    - pypika-tortoise==0.1.6
    - python-dotenv==0.20.0
    - python-multipart==0.0.5
    - python-rtmidi==1.4.9
    - pytz==2022.2.1
    - pytzdata==2020.1
    - pyyaml==6.0
    - scikit-learn==1.1.2
    - scipy==1.9.0
    - sniffio==1.2.0
    - sqladmin==0.3.0
    - sqlalchemy==1.4.40
    - tornado==6.2
    - tortoise-orm==0.19.2
    - typed-ast==1.5.4
    - unicodedata2==14.0.0
    - uvicorn==0.18.3
    - uvloop==0.16.0
    - watchfiles==0.16.1
    - websockets==10.3
    - wtforms==3.0.1
