"""initial revision

Revision ID: a56462c1c1d3
Revises: 
Create Date: 2022-04-05 12:55:37.377273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a56462c1c1d3"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pieces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pieces_id"), "pieces", ["id"], unique=False)
    op.create_index(op.f("ix_pieces_title"), "pieces", ["title"], unique=False)
    op.create_table(
        "subpieces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("piece_id", sa.Integer(), nullable=True),
        sa.Column("etr", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["piece_id"],
            ["pieces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subpieces_id"), "subpieces", ["id"], unique=False)
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "start_measure",
            sa.Integer(),
            nullable=True,
            comment="measure number of starting point of a piece",
        ),
        sa.Column(
            "end_measure",
            sa.Integer(),
            nullable=True,
            comment="measure number of ending point of a piece",
        ),
        sa.Column(
            "player", sa.String(), nullable=True, comment="scheduled player's name"
        ),
        sa.Column("piece_id", sa.Integer(), nullable=True),
        sa.Column("subpiece_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["piece_id"],
            ["pieces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subpiece_id"],
            ["subpieces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schedules_end_measure"), "schedules", ["end_measure"], unique=False
    )
    op.create_index(op.f("ix_schedules_id"), "schedules", ["id"], unique=False)
    op.create_index(
        op.f("ix_schedules_start_measure"), "schedules", ["start_measure"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schedules_start_measure"), table_name="schedules")
    op.drop_index(op.f("ix_schedules_id"), table_name="schedules")
    op.drop_index(op.f("ix_schedules_end_measure"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_index(op.f("ix_subpieces_id"), table_name="subpieces")
    op.drop_table("subpieces")
    op.drop_index(op.f("ix_pieces_title"), table_name="pieces")
    op.drop_index(op.f("ix_pieces_id"), table_name="pieces")
    op.drop_table("pieces")
    # ### end Alembic commands ###
